/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ChartParser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChartParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChartParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public ChartParser(String arg0) {
    this(freelingJNI.new_ChartParser(arg0), true);
  }

  public String getStartSymbol() {
    return freelingJNI.ChartParser_getStartSymbol(swigCPtr, this);
  }

  public void analyze(Sentence arg0) {
    freelingJNI.ChartParser_analyze__SWIG_0(swigCPtr, this, Sentence.getCPtr(arg0), arg0);
  }

  public void analyze(ListSentence arg0) {
    freelingJNI.ChartParser_analyze__SWIG_1(swigCPtr, this, ListSentence.getCPtr(arg0), arg0);
  }

}
