/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Depnode extends Node {
  private long swigCPtr;

  protected Depnode(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.Depnode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Depnode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Depnode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Depnode() {
    this(freelingJNI.new_Depnode__SWIG_0(), true);
  }

  public Depnode(String arg0) {
    this(freelingJNI.new_Depnode__SWIG_1(arg0), true);
  }

  public Depnode(Node arg0) {
    this(freelingJNI.new_Depnode__SWIG_2(Node.getCPtr(arg0), arg0), true);
  }

  public void setLink(PreorderIteratorNode arg0) {
    freelingJNI.Depnode_setLink(swigCPtr, this, PreorderIteratorNode.getCPtr(arg0), arg0);
  }

  public PreorderIteratorNode getLink() {
    return new PreorderIteratorNode(freelingJNI.Depnode_getLink(swigCPtr, this), true);
  }

  public TreeNode getLinkRef() {
    return new TreeNode(freelingJNI.Depnode_getLinkRef(swigCPtr, this), false);
  }

  public void setLabel(String arg0) {
    freelingJNI.Depnode_setLabel(swigCPtr, this, arg0);
  }

}
