/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class DepTree extends TreeDepnode {
  private long swigCPtr;

  protected DepTree(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.DepTree_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DepTree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_DepTree(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DepTree() {
    this(freelingJNI.new_DepTree__SWIG_0(), true);
  }

  public DepTree(Depnode arg0) {
    this(freelingJNI.new_DepTree__SWIG_1(Depnode.getCPtr(arg0), arg0), true);
  }

}
