/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Dictionary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Dictionary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dictionary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Dictionary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Dictionary(String arg0, String arg1, boolean arg2, String arg3, boolean invDic, boolean retok) {
    this(freelingJNI.new_Dictionary__SWIG_0(arg0, arg1, arg2, arg3, invDic, retok), true);
  }

  public Dictionary(String arg0, String arg1, boolean arg2, String arg3, boolean invDic) {
    this(freelingJNI.new_Dictionary__SWIG_1(arg0, arg1, arg2, arg3, invDic), true);
  }

  public Dictionary(String arg0, String arg1, boolean arg2, String arg3) {
    this(freelingJNI.new_Dictionary__SWIG_2(arg0, arg1, arg2, arg3), true);
  }

  public void searchForm(String arg0, ListAnalysis arg1) {
    freelingJNI.Dictionary_searchForm(swigCPtr, this, arg0, ListAnalysis.getCPtr(arg1), arg1);
  }

  public boolean annotateWord(Word arg0, ListWord arg1) {
    return freelingJNI.Dictionary_annotateWord(swigCPtr, this, Word.getCPtr(arg0), arg0, ListWord.getCPtr(arg1), arg1);
  }

  public ListString getForms(String arg0, String arg1) {
    return new ListString(freelingJNI.Dictionary_getForms(swigCPtr, this, arg0, arg1), true);
  }

  public void analyze(Sentence arg0) {
    freelingJNI.Dictionary_analyze__SWIG_0(swigCPtr, this, Sentence.getCPtr(arg0), arg0);
  }

  public void analyze(ListSentence arg0) {
    freelingJNI.Dictionary_analyze__SWIG_1(swigCPtr, this, ListSentence.getCPtr(arg0), arg0);
  }

}
