/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class HmmTagger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HmmTagger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HmmTagger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_HmmTagger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HmmTagger(String arg0, String arg1, boolean arg2, long arg3, long kb) {
    this(freelingJNI.new_HmmTagger__SWIG_0(arg0, arg1, arg2, arg3, kb), true);
  }

  public HmmTagger(String arg0, String arg1, boolean arg2, long arg3) {
    this(freelingJNI.new_HmmTagger__SWIG_1(arg0, arg1, arg2, arg3), true);
  }

  public void analyze(Sentence arg0) {
    freelingJNI.HmmTagger_analyze__SWIG_0(swigCPtr, this, Sentence.getCPtr(arg0), arg0);
  }

  public void analyze(ListSentence arg0) {
    freelingJNI.HmmTagger_analyze__SWIG_1(swigCPtr, this, ListSentence.getCPtr(arg0), arg0);
  }

}
