/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ListParagraph {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ListParagraph(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListParagraph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ListParagraph(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListParagraph() {
    this(freelingJNI.new_ListParagraph(), true);
  }

  public long size() {
    return freelingJNI.ListParagraph_size(swigCPtr, this);
  }

  public boolean empty() {
    return freelingJNI.ListParagraph_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.ListParagraph_clear(swigCPtr, this);
  }

  public void pushBack(Paragraph x) {
    freelingJNI.ListParagraph_pushBack(swigCPtr, this, Paragraph.getCPtr(x), x);
  }

  public Paragraph get(int i) {
    return new Paragraph(freelingJNI.ListParagraph_get(swigCPtr, this, i), false);
  }

}
