/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ListString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ListString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ListString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListString() {
    this(freelingJNI.new_ListString(), true);
  }

  public long size() {
    return freelingJNI.ListString_size(swigCPtr, this);
  }

  public boolean empty() {
    return freelingJNI.ListString_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.ListString_clear(swigCPtr, this);
  }

  public void pushBack(String x) {
    freelingJNI.ListString_pushBack(swigCPtr, this, x);
  }

  public String get(int i) {
    return freelingJNI.ListString_get(swigCPtr, this, i);
  }

}
