/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ListSentence {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ListSentence(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListSentence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ListSentence(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListSentence() {
    this(freelingJNI.new_ListSentence(), true);
  }

  public long size() {
    return freelingJNI.ListSentence_size(swigCPtr, this);
  }

  public boolean empty() {
    return freelingJNI.ListSentence_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.ListSentence_clear(swigCPtr, this);
  }

  public void pushBack(Sentence x) {
    freelingJNI.ListSentence_pushBack(swigCPtr, this, Sentence.getCPtr(x), x);
  }

  public Sentence get(int i) {
    return new Sentence(freelingJNI.ListSentence_get(swigCPtr, this, i), false);
  }

}
