/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ListWord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ListWord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListWord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ListWord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListWord() {
    this(freelingJNI.new_ListWord(), true);
  }

  public long size() {
    return freelingJNI.ListWord_size(swigCPtr, this);
  }

  public boolean empty() {
    return freelingJNI.ListWord_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.ListWord_clear(swigCPtr, this);
  }

  public void pushBack(Word x) {
    freelingJNI.ListWord_pushBack(swigCPtr, this, Word.getCPtr(x), x);
  }

  public Word get(int i) {
    return new Word(freelingJNI.ListWord_get(swigCPtr, this, i), false);
  }

}
