/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ListAnalysis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ListAnalysis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListAnalysis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ListAnalysis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListAnalysis() {
    this(freelingJNI.new_ListAnalysis(), true);
  }

  public long size() {
    return freelingJNI.ListAnalysis_size(swigCPtr, this);
  }

  public boolean empty() {
    return freelingJNI.ListAnalysis_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.ListAnalysis_clear(swigCPtr, this);
  }

  public void pushBack(Analysis x) {
    freelingJNI.ListAnalysis_pushBack(swigCPtr, this, Analysis.getCPtr(x), x);
  }

  public Analysis get(int i) {
    return new Analysis(freelingJNI.ListAnalysis_get(swigCPtr, this, i), false);
  }

}
