/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class MacoOptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MacoOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MacoOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_MacoOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLang(String value) {
    freelingJNI.MacoOptions_Lang_set(swigCPtr, this, value);
  }

  public String getLang() {
    return freelingJNI.MacoOptions_Lang_get(swigCPtr, this);
  }

  public void setAffixAnalysis(boolean value) {
    freelingJNI.MacoOptions_AffixAnalysis_set(swigCPtr, this, value);
  }

  public boolean getAffixAnalysis() {
    return freelingJNI.MacoOptions_AffixAnalysis_get(swigCPtr, this);
  }

  public void setMultiwordsDetection(boolean value) {
    freelingJNI.MacoOptions_MultiwordsDetection_set(swigCPtr, this, value);
  }

  public boolean getMultiwordsDetection() {
    return freelingJNI.MacoOptions_MultiwordsDetection_get(swigCPtr, this);
  }

  public void setNumbersDetection(boolean value) {
    freelingJNI.MacoOptions_NumbersDetection_set(swigCPtr, this, value);
  }

  public boolean getNumbersDetection() {
    return freelingJNI.MacoOptions_NumbersDetection_get(swigCPtr, this);
  }

  public void setPunctuationDetection(boolean value) {
    freelingJNI.MacoOptions_PunctuationDetection_set(swigCPtr, this, value);
  }

  public boolean getPunctuationDetection() {
    return freelingJNI.MacoOptions_PunctuationDetection_get(swigCPtr, this);
  }

  public void setDatesDetection(boolean value) {
    freelingJNI.MacoOptions_DatesDetection_set(swigCPtr, this, value);
  }

  public boolean getDatesDetection() {
    return freelingJNI.MacoOptions_DatesDetection_get(swigCPtr, this);
  }

  public void setQuantitiesDetection(boolean value) {
    freelingJNI.MacoOptions_QuantitiesDetection_set(swigCPtr, this, value);
  }

  public boolean getQuantitiesDetection() {
    return freelingJNI.MacoOptions_QuantitiesDetection_get(swigCPtr, this);
  }

  public void setDictionarySearch(boolean value) {
    freelingJNI.MacoOptions_DictionarySearch_set(swigCPtr, this, value);
  }

  public boolean getDictionarySearch() {
    return freelingJNI.MacoOptions_DictionarySearch_get(swigCPtr, this);
  }

  public void setProbabilityAssignment(boolean value) {
    freelingJNI.MacoOptions_ProbabilityAssignment_set(swigCPtr, this, value);
  }

  public boolean getProbabilityAssignment() {
    return freelingJNI.MacoOptions_ProbabilityAssignment_get(swigCPtr, this);
  }

  public void setOrthographicCorrection(boolean value) {
    freelingJNI.MacoOptions_OrthographicCorrection_set(swigCPtr, this, value);
  }

  public boolean getOrthographicCorrection() {
    return freelingJNI.MacoOptions_OrthographicCorrection_get(swigCPtr, this);
  }

  public void setUserMap(boolean value) {
    freelingJNI.MacoOptions_UserMap_set(swigCPtr, this, value);
  }

  public boolean getUserMap() {
    return freelingJNI.MacoOptions_UserMap_get(swigCPtr, this);
  }

  public void setNERecognition(int value) {
    freelingJNI.MacoOptions_NERecognition_set(swigCPtr, this, value);
  }

  public int getNERecognition() {
    return freelingJNI.MacoOptions_NERecognition_get(swigCPtr, this);
  }

  public void setLocutionsFile(String value) {
    freelingJNI.MacoOptions_LocutionsFile_set(swigCPtr, this, value);
  }

  public String getLocutionsFile() {
    return freelingJNI.MacoOptions_LocutionsFile_get(swigCPtr, this);
  }

  public void setQuantitiesFile(String value) {
    freelingJNI.MacoOptions_QuantitiesFile_set(swigCPtr, this, value);
  }

  public String getQuantitiesFile() {
    return freelingJNI.MacoOptions_QuantitiesFile_get(swigCPtr, this);
  }

  public void setAffixFile(String value) {
    freelingJNI.MacoOptions_AffixFile_set(swigCPtr, this, value);
  }

  public String getAffixFile() {
    return freelingJNI.MacoOptions_AffixFile_get(swigCPtr, this);
  }

  public void setProbabilityFile(String value) {
    freelingJNI.MacoOptions_ProbabilityFile_set(swigCPtr, this, value);
  }

  public String getProbabilityFile() {
    return freelingJNI.MacoOptions_ProbabilityFile_get(swigCPtr, this);
  }

  public void setDictionaryFile(String value) {
    freelingJNI.MacoOptions_DictionaryFile_set(swigCPtr, this, value);
  }

  public String getDictionaryFile() {
    return freelingJNI.MacoOptions_DictionaryFile_get(swigCPtr, this);
  }

  public void setNPdataFile(String value) {
    freelingJNI.MacoOptions_NPdataFile_set(swigCPtr, this, value);
  }

  public String getNPdataFile() {
    return freelingJNI.MacoOptions_NPdataFile_get(swigCPtr, this);
  }

  public void setPunctuationFile(String value) {
    freelingJNI.MacoOptions_PunctuationFile_set(swigCPtr, this, value);
  }

  public String getPunctuationFile() {
    return freelingJNI.MacoOptions_PunctuationFile_get(swigCPtr, this);
  }

  public void setCorrectorFile(String value) {
    freelingJNI.MacoOptions_CorrectorFile_set(swigCPtr, this, value);
  }

  public String getCorrectorFile() {
    return freelingJNI.MacoOptions_CorrectorFile_get(swigCPtr, this);
  }

  public void setUserMapFile(String value) {
    freelingJNI.MacoOptions_UserMapFile_set(swigCPtr, this, value);
  }

  public String getUserMapFile() {
    return freelingJNI.MacoOptions_UserMapFile_get(swigCPtr, this);
  }

  public void setDecimal(String value) {
    freelingJNI.MacoOptions_Decimal_set(swigCPtr, this, value);
  }

  public String getDecimal() {
    return freelingJNI.MacoOptions_Decimal_get(swigCPtr, this);
  }

  public void setThousand(String value) {
    freelingJNI.MacoOptions_Thousand_set(swigCPtr, this, value);
  }

  public String getThousand() {
    return freelingJNI.MacoOptions_Thousand_get(swigCPtr, this);
  }

  public void setProbabilityThreshold(double value) {
    freelingJNI.MacoOptions_ProbabilityThreshold_set(swigCPtr, this, value);
  }

  public double getProbabilityThreshold() {
    return freelingJNI.MacoOptions_ProbabilityThreshold_get(swigCPtr, this);
  }

  public void setInverseDict(boolean value) {
    freelingJNI.MacoOptions_InverseDict_set(swigCPtr, this, value);
  }

  public boolean getInverseDict() {
    return freelingJNI.MacoOptions_InverseDict_get(swigCPtr, this);
  }

  public void setRetokContractions(boolean value) {
    freelingJNI.MacoOptions_RetokContractions_set(swigCPtr, this, value);
  }

  public boolean getRetokContractions() {
    return freelingJNI.MacoOptions_RetokContractions_get(swigCPtr, this);
  }

  public MacoOptions(String arg0) {
    this(freelingJNI.new_MacoOptions(arg0), true);
  }

  public void setActiveModules(boolean arg0, boolean arg1, boolean arg2, boolean arg3, boolean arg4, boolean arg5, boolean arg6, boolean arg7, boolean arg8, boolean arg9, boolean arg10) {
    freelingJNI.MacoOptions_setActiveModules(swigCPtr, this, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
  }

  public void setDataFiles(String arg0, String arg1, String arg2, String arg3, String arg4, String arg5, String arg6, String arg7, String arg8) {
    freelingJNI.MacoOptions_setDataFiles(swigCPtr, this, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
  }

  public void setNummericalPoints(String arg0, String arg1) {
    freelingJNI.MacoOptions_setNummericalPoints(swigCPtr, this, arg0, arg1);
  }

  public void setThreshold(double arg0) {
    freelingJNI.MacoOptions_setThreshold(swigCPtr, this, arg0);
  }

  public void setInverseDictionary(boolean arg0) {
    freelingJNI.MacoOptions_setInverseDictionary(swigCPtr, this, arg0);
  }

  public void setRetokenizeContractions(boolean arg0) {
    freelingJNI.MacoOptions_setRetokenizeContractions(swigCPtr, this, arg0);
  }

}
