/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Node {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Node(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Node obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Node(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Node() {
    this(freelingJNI.new_Node__SWIG_0(), true);
  }

  public Node(String arg0) {
    this(freelingJNI.new_Node__SWIG_1(arg0), true);
  }

  public String getNodeId() {
    return freelingJNI.Node_getNodeId(swigCPtr, this);
  }

  public void setNodeId(String arg0) {
    freelingJNI.Node_setNodeId(swigCPtr, this, arg0);
  }

  public String getLabel() {
    return freelingJNI.Node_getLabel(swigCPtr, this);
  }

  public Word getWord() {
    return new Word(freelingJNI.Node_getWord(swigCPtr, this), true);
  }

  public void setLabel(String arg0) {
    freelingJNI.Node_setLabel(swigCPtr, this, arg0);
  }

  public void setWord(Word arg0) {
    freelingJNI.Node_setWord(swigCPtr, this, Word.getCPtr(arg0), arg0);
  }

  public boolean isHead() {
    return freelingJNI.Node_isHead(swigCPtr, this);
  }

  public void setHead(boolean arg0) {
    freelingJNI.Node_setHead(swigCPtr, this, arg0);
  }

  public boolean isChunk() {
    return freelingJNI.Node_isChunk(swigCPtr, this);
  }

  public void setChunk(int arg0) {
    freelingJNI.Node_setChunk(swigCPtr, this, arg0);
  }

  public int getChunkOrd() {
    return freelingJNI.Node_getChunkOrd(swigCPtr, this);
  }

}
