/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class PairDoubleString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PairDoubleString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairDoubleString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_PairDoubleString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PairDoubleString() {
    this(freelingJNI.new_PairDoubleString__SWIG_0(), true);
  }

  public PairDoubleString(double first, String second) {
    this(freelingJNI.new_PairDoubleString__SWIG_1(first, second), true);
  }

  public PairDoubleString(PairDoubleString p) {
    this(freelingJNI.new_PairDoubleString__SWIG_2(PairDoubleString.getCPtr(p), p), true);
  }

  public void setFirst(double value) {
    freelingJNI.PairDoubleString_first_set(swigCPtr, this, value);
  }

  public double getFirst() {
    return freelingJNI.PairDoubleString_first_get(swigCPtr, this);
  }

  public void setSecond(String value) {
    freelingJNI.PairDoubleString_second_set(swigCPtr, this, value);
  }

  public String getSecond() {
    return freelingJNI.PairDoubleString_second_get(swigCPtr, this);
  }

}
