/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Paragraph extends ListSentence {
  private long swigCPtr;

  protected Paragraph(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.Paragraph_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Paragraph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Paragraph(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Paragraph() {
    this(freelingJNI.new_Paragraph(), true);
  }

}
