/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class ParseTree extends TreeNode {
  private long swigCPtr;

  protected ParseTree(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.ParseTree_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParseTree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_ParseTree(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ParseTree() {
    this(freelingJNI.new_ParseTree__SWIG_0(), true);
  }

  public ParseTree(Node arg0) {
    this(freelingJNI.new_ParseTree__SWIG_1(Node.getCPtr(arg0), arg0), true);
  }

}
