/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class PreorderIteratorNode extends GenericIteratorNode {
  private long swigCPtr;

  protected PreorderIteratorNode(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.PreorderIteratorNode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PreorderIteratorNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_PreorderIteratorNode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PreorderIteratorNode() {
    this(freelingJNI.new_PreorderIteratorNode__SWIG_0(), true);
  }

  public PreorderIteratorNode(PreorderIteratorNode arg0) {
    this(freelingJNI.new_PreorderIteratorNode__SWIG_1(PreorderIteratorNode.getCPtr(arg0), arg0), true);
  }

  public PreorderIteratorNode(TreeNode arg0) {
    this(freelingJNI.new_PreorderIteratorNode__SWIG_2(TreeNode.getCPtr(arg0), arg0), true);
  }

  public PreorderIteratorNode(SiblingIteratorNode arg0) {
    this(freelingJNI.new_PreorderIteratorNode__SWIG_3(SiblingIteratorNode.getCPtr(arg0), arg0), true);
  }

  public PreorderIteratorNode operator_increment() {
    return new PreorderIteratorNode(freelingJNI.PreorderIteratorNode_operator_increment__SWIG_0(swigCPtr, this), false);
  }

  public PreorderIteratorNode operator_decrement() {
    return new PreorderIteratorNode(freelingJNI.PreorderIteratorNode_operator_decrement__SWIG_0(swigCPtr, this), false);
  }

  public PreorderIteratorNode operator_increment(int arg0) {
    return new PreorderIteratorNode(freelingJNI.PreorderIteratorNode_operator_increment__SWIG_1(swigCPtr, this, arg0), true);
  }

  public PreorderIteratorNode operator_decrement(int arg0) {
    return new PreorderIteratorNode(freelingJNI.PreorderIteratorNode_operator_decrement__SWIG_1(swigCPtr, this, arg0), true);
  }

}
