/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Probabilities {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Probabilities(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Probabilities obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Probabilities(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Probabilities(String arg0, String arg1, double arg2) {
    this(freelingJNI.new_Probabilities(arg0, arg1, arg2), true);
  }

  public void annotateWord(Word arg0) {
    freelingJNI.Probabilities_annotateWord(swigCPtr, this, Word.getCPtr(arg0), arg0);
  }

  public void setActivateGuesser(boolean arg0) {
    freelingJNI.Probabilities_setActivateGuesser(swigCPtr, this, arg0);
  }

  public void analyze(Sentence arg0) {
    freelingJNI.Probabilities_analyze__SWIG_0(swigCPtr, this, Sentence.getCPtr(arg0), arg0);
  }

  public void analyze(ListSentence arg0) {
    freelingJNI.Probabilities_analyze__SWIG_1(swigCPtr, this, ListSentence.getCPtr(arg0), arg0);
  }

}
