/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class SemanticDB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SemanticDB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SemanticDB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_SemanticDB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SemanticDB(String arg0) {
    this(freelingJNI.new_SemanticDB(arg0), true);
  }

  public void getWNKeys(String arg0, String arg1, String arg2, SWIGTYPE_p_std__listT_std__pairT_std__wstring_std__wstring_t_t arg3) {
    freelingJNI.SemanticDB_getWNKeys(swigCPtr, this, arg0, arg1, arg2, SWIGTYPE_p_std__listT_std__pairT_std__wstring_std__wstring_t_t.getCPtr(arg3));
  }

  public ListString getSenseWords(String arg0) {
    return new ListString(freelingJNI.SemanticDB_getSenseWords(swigCPtr, this, arg0), true);
  }

  public ListString getWordSenses(String arg0, String arg1, String arg2) {
    return new ListString(freelingJNI.SemanticDB_getWordSenses(swigCPtr, this, arg0, arg1, arg2), true);
  }

  public SenseInfo getSenseInfo(String arg0) {
    return new SenseInfo(freelingJNI.SemanticDB_getSenseInfo(swigCPtr, this, arg0), true);
  }

}
