/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class SenseInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SenseInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SenseInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_SenseInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSense(String value) {
    freelingJNI.SenseInfo_sense_set(swigCPtr, this, value);
  }

  public String getSense() {
    return freelingJNI.SenseInfo_sense_get(swigCPtr, this);
  }

  public void setParents(ListString value) {
    freelingJNI.SenseInfo_parents_set(swigCPtr, this, ListString.getCPtr(value), value);
  }

  public ListString getParents() {
    long cPtr = freelingJNI.SenseInfo_parents_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ListString(cPtr, false);
  }

  public void setSemfile(String value) {
    freelingJNI.SenseInfo_semfile_set(swigCPtr, this, value);
  }

  public String getSemfile() {
    return freelingJNI.SenseInfo_semfile_get(swigCPtr, this);
  }

  public void setWords(ListString value) {
    freelingJNI.SenseInfo_words_set(swigCPtr, this, ListString.getCPtr(value), value);
  }

  public ListString getWords() {
    long cPtr = freelingJNI.SenseInfo_words_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ListString(cPtr, false);
  }

  public void setTonto(ListString value) {
    freelingJNI.SenseInfo_tonto_set(swigCPtr, this, ListString.getCPtr(value), value);
  }

  public ListString getTonto() {
    long cPtr = freelingJNI.SenseInfo_tonto_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ListString(cPtr, false);
  }

  public SenseInfo(String arg0, String arg1) {
    this(freelingJNI.new_SenseInfo(arg0, arg1), true);
  }

  public String getParentsString() {
    return freelingJNI.SenseInfo_getParentsString(swigCPtr, this);
  }

}
