/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Sentence extends ListWord {
  private long swigCPtr;

  protected Sentence(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.Sentence_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Sentence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Sentence(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Sentence() {
    this(freelingJNI.new_Sentence__SWIG_0(), true);
  }

  public Sentence(ListWord arg0) {
    this(freelingJNI.new_Sentence__SWIG_1(ListWord.getCPtr(arg0), arg0), true);
  }

  public Sentence(Sentence arg0) {
    this(freelingJNI.new_Sentence__SWIG_2(Sentence.getCPtr(arg0), arg0), true);
  }

  public Sentence operator_assignment(Sentence arg0) {
    return new Sentence(freelingJNI.Sentence_operator_assignment(swigCPtr, this, Sentence.getCPtr(arg0), arg0), false);
  }

  public long numKbest() {
    return freelingJNI.Sentence_numKbest(swigCPtr, this);
  }

  public void setParseTree(ParseTree arg0) {
    freelingJNI.Sentence_setParseTree(swigCPtr, this, ParseTree.getCPtr(arg0), arg0);
  }

  public ParseTree getParseTree() {
    return new ParseTree(freelingJNI.Sentence_getParseTree(swigCPtr, this), false);
  }

  public boolean isParsed() {
    return freelingJNI.Sentence_isParsed(swigCPtr, this);
  }

  public DepTree getDepTree() {
    return new DepTree(freelingJNI.Sentence_getDepTree(swigCPtr, this), false);
  }

  public void setDepTree(DepTree arg0) {
    freelingJNI.Sentence_setDepTree(swigCPtr, this, DepTree.getCPtr(arg0), arg0);
  }

  public boolean isDepParsed() {
    return freelingJNI.Sentence_isDepParsed(swigCPtr, this);
  }

  public VectorWord getWords() {
    return new VectorWord(freelingJNI.Sentence_getWords(swigCPtr, this), true);
  }

  public SWIGTYPE_p_sentence__iterator wordsBegin() {
    return new SWIGTYPE_p_sentence__iterator(freelingJNI.Sentence_wordsBegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_sentence__iterator wordsEnd() {
    return new SWIGTYPE_p_sentence__iterator(freelingJNI.Sentence_wordsEnd(swigCPtr, this), true);
  }

}
