/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class SiblingIteratorDepnode extends GenericIteratorDepnode {
  private long swigCPtr;

  protected SiblingIteratorDepnode(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.SiblingIteratorDepnode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SiblingIteratorDepnode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_SiblingIteratorDepnode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SiblingIteratorDepnode() {
    this(freelingJNI.new_SiblingIteratorDepnode__SWIG_0(), true);
  }

  public SiblingIteratorDepnode(SiblingIteratorDepnode arg0) {
    this(freelingJNI.new_SiblingIteratorDepnode__SWIG_1(SiblingIteratorDepnode.getCPtr(arg0), arg0), true);
  }

  public SiblingIteratorDepnode(TreeDepnode arg0) {
    this(freelingJNI.new_SiblingIteratorDepnode__SWIG_2(TreeDepnode.getCPtr(arg0), arg0), true);
  }

  public SiblingIteratorDepnode operator_increment() {
    return new SiblingIteratorDepnode(freelingJNI.SiblingIteratorDepnode_operator_increment__SWIG_0(swigCPtr, this), false);
  }

  public SiblingIteratorDepnode operator_decrement() {
    return new SiblingIteratorDepnode(freelingJNI.SiblingIteratorDepnode_operator_decrement__SWIG_0(swigCPtr, this), false);
  }

  public SiblingIteratorDepnode operator_increment(int arg0) {
    return new SiblingIteratorDepnode(freelingJNI.SiblingIteratorDepnode_operator_increment__SWIG_1(swigCPtr, this, arg0), true);
  }

  public SiblingIteratorDepnode operator_decrement(int arg0) {
    return new SiblingIteratorDepnode(freelingJNI.SiblingIteratorDepnode_operator_decrement__SWIG_1(swigCPtr, this, arg0), true);
  }

}
