/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class SiblingIteratorNode extends GenericIteratorNode {
  private long swigCPtr;

  protected SiblingIteratorNode(long cPtr, boolean cMemoryOwn) {
    super(freelingJNI.SiblingIteratorNode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SiblingIteratorNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_SiblingIteratorNode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SiblingIteratorNode() {
    this(freelingJNI.new_SiblingIteratorNode__SWIG_0(), true);
  }

  public SiblingIteratorNode(SiblingIteratorNode arg0) {
    this(freelingJNI.new_SiblingIteratorNode__SWIG_1(SiblingIteratorNode.getCPtr(arg0), arg0), true);
  }

  public SiblingIteratorNode(TreeNode arg0) {
    this(freelingJNI.new_SiblingIteratorNode__SWIG_2(TreeNode.getCPtr(arg0), arg0), true);
  }

  public SiblingIteratorNode operator_increment() {
    return new SiblingIteratorNode(freelingJNI.SiblingIteratorNode_operator_increment__SWIG_0(swigCPtr, this), false);
  }

  public SiblingIteratorNode operator_decrement() {
    return new SiblingIteratorNode(freelingJNI.SiblingIteratorNode_operator_decrement__SWIG_0(swigCPtr, this), false);
  }

  public SiblingIteratorNode operator_increment(int arg0) {
    return new SiblingIteratorNode(freelingJNI.SiblingIteratorNode_operator_increment__SWIG_1(swigCPtr, this, arg0), true);
  }

  public SiblingIteratorNode operator_decrement(int arg0) {
    return new SiblingIteratorNode(freelingJNI.SiblingIteratorNode_operator_decrement__SWIG_1(swigCPtr, this, arg0), true);
  }

}
