/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Splitter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Splitter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Splitter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Splitter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Splitter(String arg0) {
    this(freelingJNI.new_Splitter(arg0), true);
  }

  public ListSentence split(ListWord arg0, boolean arg1) {
    return new ListSentence(freelingJNI.Splitter_split(swigCPtr, this, ListWord.getCPtr(arg0), arg0, arg1), true);
  }

}
