/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class Util {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Util(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Util obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_Util(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void initLocale(String arg0) {
    freelingJNI.Util_initLocale(arg0);
  }

  public static int wstring2int(String arg0) {
    return freelingJNI.Util_wstring2int(arg0);
  }

  public static String int2wstring(int arg0) {
    return freelingJNI.Util_int2wstring(arg0);
  }

  public static double wstring2double(String arg0) {
    return freelingJNI.Util_wstring2double(arg0);
  }

  public static String double2wstring(double arg0) {
    return freelingJNI.Util_double2wstring(arg0);
  }

  public static SWIGTYPE_p_long_double wstring2longdouble(String arg0) {
    return new SWIGTYPE_p_long_double(freelingJNI.Util_wstring2longdouble(arg0), true);
  }

  public static String longdouble2wstring(SWIGTYPE_p_long_double arg0) {
    return freelingJNI.Util_longdouble2wstring(SWIGTYPE_p_long_double.getCPtr(arg0));
  }

  public static String vector2wstring(VectorString arg0, String arg1) {
    return freelingJNI.Util_vector2wstring(VectorString.getCPtr(arg0), arg0, arg1);
  }

  public static String list2wstring(ListString arg0, String arg1) {
    return freelingJNI.Util_list2wstring(ListString.getCPtr(arg0), arg0, arg1);
  }

  public static String pairlist2wstring(SWIGTYPE_p_std__listT_std__pairT_std__wstring_double_t_t arg0, String arg1, String arg2) {
    return freelingJNI.Util_pairlist2wstring(SWIGTYPE_p_std__listT_std__pairT_std__wstring_double_t_t.getCPtr(arg0), arg1, arg2);
  }

  public static ListString wstring2list(String arg0, String arg1) {
    return new ListString(freelingJNI.Util_wstring2list(arg0, arg1), true);
  }

  public static VectorString wstring2vector(String arg0, String arg1) {
    return new VectorString(freelingJNI.Util_wstring2vector(arg0, arg1), true);
  }

  public Util() {
    this(freelingJNI.new_Util(), true);
  }

}
