/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class VectorPairDoubleString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorPairDoubleString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorPairDoubleString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_VectorPairDoubleString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorPairDoubleString() {
    this(freelingJNI.new_VectorPairDoubleString__SWIG_0(), true);
  }

  public VectorPairDoubleString(long n) {
    this(freelingJNI.new_VectorPairDoubleString__SWIG_1(n), true);
  }

  public long size() {
    return freelingJNI.VectorPairDoubleString_size(swigCPtr, this);
  }

  public long capacity() {
    return freelingJNI.VectorPairDoubleString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    freelingJNI.VectorPairDoubleString_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return freelingJNI.VectorPairDoubleString_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.VectorPairDoubleString_clear(swigCPtr, this);
  }

  public void pushBack(PairDoubleString x) {
    freelingJNI.VectorPairDoubleString_pushBack(swigCPtr, this, PairDoubleString.getCPtr(x), x);
  }

  public PairDoubleString get(int i) {
    return new PairDoubleString(freelingJNI.VectorPairDoubleString_get(swigCPtr, this, i), false);
  }

  public void set(int i, PairDoubleString val) {
    freelingJNI.VectorPairDoubleString_set(swigCPtr, this, i, PairDoubleString.getCPtr(val), val);
  }

}
