/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class VectorString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_VectorString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorString() {
    this(freelingJNI.new_VectorString__SWIG_0(), true);
  }

  public VectorString(long n) {
    this(freelingJNI.new_VectorString__SWIG_1(n), true);
  }

  public long size() {
    return freelingJNI.VectorString_size(swigCPtr, this);
  }

  public long capacity() {
    return freelingJNI.VectorString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    freelingJNI.VectorString_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return freelingJNI.VectorString_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.VectorString_clear(swigCPtr, this);
  }

  public void pushBack(String x) {
    freelingJNI.VectorString_pushBack(swigCPtr, this, x);
  }

  public String get(int i) {
    return freelingJNI.VectorString_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    freelingJNI.VectorString_set(swigCPtr, this, i, val);
  }

}
