/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class VectorListInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorListInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorListInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_VectorListInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorListInt() {
    this(freelingJNI.new_VectorListInt__SWIG_0(), true);
  }

  public VectorListInt(long n) {
    this(freelingJNI.new_VectorListInt__SWIG_1(n), true);
  }

  public long size() {
    return freelingJNI.VectorListInt_size(swigCPtr, this);
  }

  public long capacity() {
    return freelingJNI.VectorListInt_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    freelingJNI.VectorListInt_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return freelingJNI.VectorListInt_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.VectorListInt_clear(swigCPtr, this);
  }

  public void pushBack(ListInt x) {
    freelingJNI.VectorListInt_pushBack(swigCPtr, this, ListInt.getCPtr(x), x);
  }

  public ListInt get(int i) {
    return new ListInt(freelingJNI.VectorListInt_get(swigCPtr, this, i), false);
  }

  public void set(int i, ListInt val) {
    freelingJNI.VectorListInt_set(swigCPtr, this, i, ListInt.getCPtr(val), val);
  }

}
