/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.upc.freeling;

public class VectorListString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorListString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorListString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        freelingJNI.delete_VectorListString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorListString() {
    this(freelingJNI.new_VectorListString__SWIG_0(), true);
  }

  public VectorListString(long n) {
    this(freelingJNI.new_VectorListString__SWIG_1(n), true);
  }

  public long size() {
    return freelingJNI.VectorListString_size(swigCPtr, this);
  }

  public long capacity() {
    return freelingJNI.VectorListString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    freelingJNI.VectorListString_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return freelingJNI.VectorListString_empty(swigCPtr, this);
  }

  public void clear() {
    freelingJNI.VectorListString_clear(swigCPtr, this);
  }

  public void pushBack(ListString x) {
    freelingJNI.VectorListString_pushBack(swigCPtr, this, ListString.getCPtr(x), x);
  }

  public ListString get(int i) {
    return new ListString(freelingJNI.VectorListString_get(swigCPtr, this, i), false);
  }

  public void set(int i, ListString val) {
    freelingJNI.VectorListString_set(swigCPtr, this, i, ListString.getCPtr(val), val);
  }

}
